### ISSUE TITLE
uncaught exception in !tcp_req

### ISSUE THREAD

**Issue by kevinanewman** [pgiri/pycos#20]
I've been getting the following error, seems to come sometimes with a Python crash of the dispy shared scheduler... not sure if that's related or not, but maybe there should be some better way of handling whatever the error is here.  Let me know if there's anything I can do to help.

2019-04-05 13:29:19 pycos - uncaught exception in !tcp_req/1734014532424:
Traceback (most recent call last):
  File "c:\users\public\Python3.6.7\lib\site-packages\pycos\__init__.py", line 3669, in _schedule
    retval = task._generator.throw(*exc)
  File "c:\users\public\Python3.6.7\Lib\site-packages\dispy\dispyscheduler.py", line 382, in tcp_req
    msg = yield conn.recv_msg()
  File "c:\users\public\Python3.6.7\lib\site-packages\pycos\__init__.py", line 3669, in _schedule
    retval = task._generator.throw(*exc)
  File "c:\users\public\Python3.6.7\lib\site-packages\pycos\__init__.py", line 899, in _async_recv_msg
    data = yield self.recvall(n)
OSError: 64

Any help appreciated, thank you!

**Comment by pgiri** [comment]
This seems to be an issue caused in dispyscheduler, likely because there is a network issue (such as client / node disconnected)?

**Comment by kevinanewman** [comment]
Yes, it seems the dispyscheduler crashed, once I restarted it all the nodes were available.  Anything is possible as far as the network goes, but the machines are in a dedicated server environment and are all connected the same router so we wouldn't expect any problems.  The error message showed up several times before the scheduler eventually crashed, so it's hard to say if there were multiple problems in short succession or over time.

Any ideas for how I might be able to troubleshoot this?  Thank you!

**Comment by pgiri** [comment]
What version of dispy are you using? Exception trace when it crashed, if available, would help.

**Comment by kevinanewman** [comment]
python 3.6.7
dispy 4.10.6
pycos 4.8.11

I'd take recommendations for getting the exception trace - maybe traceback?  As it is all I have it what shows up on the console.

Thanks again.

**Comment by pgiri** [comment]
It is possible dispyscheduler hasn't crashed. If all that is shown is the trace above, then dispyscheduler would continue to work. The task that generated the exception (processing a network connection) is thrown away but dispyscheduler itself will respond to new requests. 'OSError 64' implies, as mentioned above, network error that can't be fixed in dispy.

Attached is a patch that will print the address that seems to cause problems in your case.
[conn_err_msg.txt](https://github.com/pgiri/pycos/files/3059135/conn_err_msg.txt)

**Comment by kevinanewman** [comment]
The dispyscheduler definitely crashed... perhaps from something else if not from this exception.  Windows popped up a "Python has encountered an error" dialog box, which terminated the python that launched the scheduler.  I will take a look at the patch and let you know what I learn, thank you!

**Comment by kevinanewman** [comment]
Ok, so here's what I've seen... it seems like a node from outside our network is trying to connect to our dispyscheduler.  The IP is 10.170.170.41, which is not one of my nodes and doesn't look like it's anything on our network.  Anyway, I have grabbed the error messages from the dispycheduler and the dispynodes.

Have you seen anything like this before?  I'm not sure what to make of it.  Windows firewall is all activated, with an exception for Python since we had to enable that to get the nodes to see each other.

[dispynode_errorlog.txt](https://github.com/pgiri/pycos/files/3065217/dispynode_errorlog.txt)
[dispyscheduler_errorlog.txt](https://github.com/pgiri/pycos/files/3065218/dispyscheduler_errorlog.txt)

The scheduler did NOT crash in this instance.

**Comment by kevinanewman** [comment]
Turns out it's the US EPA security scanner... don't think I'll be able to deny the TCP requests or block them.

**Comment by pgiri** [comment]
You may be able to configure firewall to allow connections only from within your network or prevent connections from offending IP address? The above logs show connections to httpd (port 8181), not dispyscheduler port.

In any case, dispyscheduler is not supposed to crash from invalid connections. If it does, the log showing crash may help.

**Comment by kevinanewman** [comment]
So I modified the firewall to block 10.170.170.41 and it's been almost 24 hours with no error messages so that seems like a good sign so far.  No idea if the sysadmins will unblock it, but I'll update if I see any other problems.  Thanks for your help.
