### ISSUE TITLE
ZeroDivisionError in __status_proc()

### ISSUE THREAD

**Issue by skozlovf** [pgiri/pycos#24]
I randomly get `ZeroDivisionError: float division by zero` after tasks finishing.

```
2019-10-18 11:41:39 dispycos - uncaught exception in ~__status_proc/140198599855712:
Traceback (most recent call last):
  File "pycos/__init__.py", line 3611, in _schedule
    retval = task._generator.send(task._value)
  File "pycos/dispycos.py", line 864, in __status_proc
    node.load = float(node.cpus_used) / len(node.servers)
ZeroDivisionError: float division by zero

2019-10-18 11:41:39 dispycos - ignoring invalid recipient to "send"
2019-10-18 11:41:39 dispycos - ignoring invalid recipient to "send"
2019-10-18 11:41:39 dispycos - invalid task 140198599855712 to resume
2019-10-18 11:41:39 dispycos - invalid task 140198599855712 to resume
```

How I run, briefly:
* Start remote servers with `dispycosnode`.
* Create remote tasks and run computation.
* Monitor the tasks in special "monitor" task.
* Wait for "monitor" task finishing.
* Close computation.
* Stop remote servers.

The error may happen after successful processing or on some exception in remote task. On remote exceptions and local env/docker cluster it happens more frequently than in EC2 env.

**Comment by pgiri** [comment]
This may be because the messages from node arrive in different order than expected (i.e., NodeClosed message arriving before ServerClosed messages do). I will commit fix in the next couple of days.

**Comment by skozlovf** [comment]
Still happens sometimes in local docker-based nodes when remote task finishes (with or without an error) or task manager raises an error. But it doesn't happen with AWS nodes after your commit.
Can't reproduce, happens rarely.
