### ISSUE TITLE
_async_recv_msg can never succeed

### ISSUE THREAD

**Issue by UnitedMarsupials** [pgiri/pycos#6]
The current implementation of `_async_recv_msg` has `raise`, where its sibling `_sync_recv_msg` has `return`. The asynchronous variant can not possibly end successfully -- it _always_ raises the `StopIteration` exception...

And all the scripts -- including the `sample.py` bundled with dispy -- hang after the `cluster.submit()` loop.

I do not understand, how it can work for _anyone_ - nor how did it pass testing :(

With the following patch applied, I can get dispy's `sample.py` to actually work:
```diff
--- pycos/__init__.py       2018-08-25 18:16:12.000000000 -0400
+++ pycos/__init__.py       2018-08-28 19:47:00.572667818 -0400
@@ -883,5 +883,5 @@
             if err.args[0] == 'hangup':
                 # raise socket.error(errno.EPIPE, 'Insufficient data')
-                raise StopIteration(b'')
+                return b''
             else:
                 raise
@@ -897,5 +897,5 @@
                 if err.args[0] == 'hangup':
                     # raise socket.error(errno.EPIPE, 'Insufficient data')
-                    raise StopIteration(b'')
+                    return b''
                 else:
                     raise
@@ -903,7 +903,7 @@
                 # raise socket.error(errno.EPIPE, 'Insufficient data: %s / %s' % (len(data), n))
                 raise StopIteration(b'')
-            raise StopIteration(data)
+            return data
         else:
-            raise StopIteration(b'')
+            return b''
 
     def _sync_recv_msg(self):
```

Although dispynode still throws for every job-submission:
```
2018-08-28 19:53:00 pycos - uncaught exception in !_send_job_reply/140586224979496:
Traceback (most recent call last):
  File "/meow/bin/dispynode.py", line 1459, in _send_job_reply
    raise StopIteration(status)
StopIteration: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/meow/lib/python3.7/site-packages/pycos/__init__.py", line 3667, in _schedule 
    retval = task._generator.send(task._value)
RuntimeError: generator raised StopIteration
```

**Comment by UnitedMarsupials** [comment]
FWIW, I'm using dispy with Python-3.7.0 on some machines (Linux RHEL6), while still using Python-3.6.6 on FreeBSD.

**Comment by UnitedMarsupials** [comment]
Yes, after downgrading Python to 3.6.6, things seem to work...
